language: go

sudo: required

services:
  - docker

go:
  - 1.5

before_install:
  - echo "Dpkg::Options { \"--force-confdef\"; \"--force-confold\"; }" |sudo tee -a /etc/apt/apt.conf.d/local
  - sudo apt-get install apt-transport-https ca-certificates
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip2 install --upgrade pip setuptools wheel docker-compose
  - sudo docker-compose --version

install:
  - go get -v -d

before_script:
  - docker version
  - make binary-linux-amd64
  - chmod +x bin/linux/amd64/local-persist
  - sudo ./bin/linux/amd64/local-persist &

script:
  - ./scripts/integration.sh
  - make test
